- app/pages/Main.vue
- app/pages/paths/teacher/request/Notice.vue
- app/pages/paths/teacher/request/Wrapper.vue
- app/router/routers/teacher.js
- app/src/api/notice.js
can change mainpage notice in teacher page
> add mainpage notice

- app/router/index.js
Closes https://github.com/dimigoin/dimigoin-front/issues/75
> Set history mode of vue-router

- app/components/CircleCard.vue
- app/dimiru/components/DimiLongInput.vue
- app/pages/paths/request/Afterschool.vue
- app/pages/paths/request/Circle.vue
- app/src/util/days.js
> fix: a lot of issues

- app/pages/paths/request/Afterschool.vue
> fix: change text in afterschool request

- app/scss/theme.scss
> feat: custom text selection style

- app/components/CircleCard.vue
- app/dimiru/components/DimiLongInput.vue
- app/pages/paths/request/Circle.vue
> fix: update circle request ui text

- app/src/api/book/book.service.js
> fix: update book request api payload

- app/pages/paths/request/Afterschool.vue
> feat(service): update max request count of afterschool

- app/components/CircleCard.vue
- app/src/api/circle/circle.struct.js
> refactor: change api payload in circle

- app/components/CircleCard.vue
- app/dimiru/components/DimiLongInput.vue
> fix(style): replace style of input height with scoped in CircleCard (#118)

- app/pages/paths/request/Book.vue
잘못된 변수명, 불필요한 스타일 제거했습니다.
This closes #101, closes #102
> fix: book request

- app/src/api/book/book.service.js
> fix(api): update api payload of book management

- app/pages/paths/management/ManageBook.vue
> fix(style): remove useless style of last item in book management

- app/pages/paths/teacher/assignment/Assignment.vue
- app/src/api/assignment/assignment.struct.js
> fix: change DateTime in assignment to Unix Timestamp

- app/pages/paths/management/ManageCircle.vue
> fix: remove duplicated title in manage-circle

- app/pages/paths/management/ManageBook.vue
> feat(service): add option that hides evaluated book request

- app/pages/paths/management/ManageDets.vue
- app/pages/paths/request/Afterschool.vue
- app/pages/paths/request/Dets.vue
> feat(message): change helper message in some pages

- build/webpack.dev.conf.js
- index.html
> chore(dev): fix history api fallback

- index.html
> fix: apply conditional rendering in base tag

- app/components/AssignmentBase.vue
- app/components/CircleCard.vue
- app/components/MealGroup.vue
- app/pages/paths/request/Ingang.vue
> fix(style): apply essential scoped style

- .browserlistrc
> fix(browser): support old browser

- app/pages/paths/request/Counsel.vue
Closes #158 
Previews for iPhone X, Galaxy S5
> fix(ui): line-height for counsel request mobile list

- app/pages/Main.vue
> fix: min height in info section

- app/src/api/afterschool/afterschool.service.js
> chore: remove 404 handler in getGradeAfterschool

- app/components/AssignmentBase.vue
> feat: add time information of assignment's deadline

- app/pages/paths/management/ManageAfterschool.vue
* set not to delete unchecked activity
* set not to update activities when nothing checked
* set interval before update activities
Closes #110
> fix: afterschool manage page

- app/pages/paths/management/ManageCounsel.vue
> fix(style): remove useless padding and border

- app/pages/paths/management/ManageCounsel.vue
- app/pages/paths/request/Counsel.vue
before: `Wednesday ( 03월 20일 ) 07시 50분 ~08시 30분`
after: `수요일 ( 03월 20일 ) 07시 50분 ~08시 30분`
closes #175.
> Change locale date fns

- app/pages/paths/management/ManageAfterschool.vue
- app/src/api/afterschool/afterschool.service.js
> feat: add afterschool request list excel download button

- app/pages/paths/management/ManageBook.vue
- app/pages/paths/management/ManageCounsel.vue
- app/pages/paths/management/ManageDets.vue
- app/pages/paths/management/ManageIngang.vue
- app/src/api/assignment/assignment.service.js
- app/src/api/book/book.service.js
- app/src/api/counsel/counsel.service.js
- app/src/api/dets/dets.service.js
- app/src/api/ingang/index.js
- app/src/api/ingang/ingang.service.js
> fix: check permission downloading excel file in management

- app/pages/paths/management/ManageIngang.vue
- app/pages/paths/request/Ingang.vue
- app/src/api/ingang/index.js
- app/src/api/ingang/ingang.service.js
- app/src/api/ingang/ingang.struct.js
> refactor: reform ingang service

- app/components/AssignmentBase.vue
> feat: add helper message box in assignment wrapper

- app/components/AssignmentBase.vue
실수로 조건을 안 넣어서 항상 없다는 메시지가 출력됐어요
> fix: show helper message when assignment doesn't exist

- app/pages/paths/management/ManageIngang.vue
> refactor: use ButtonGroup in ingang manage

- app/pages/paths/request/Counsel.vue
> fix(service): renew career counsel to employment counsel

- app/pages/paths/management/ManageMentoring.vue
- app/pages/paths/request/Mentoring.vue
> fix: mentoring notice date format

- app/pages/paths/management/ManageMentoring.vue
This closes #224 and closes #227
> Fix some errors in mentoring request/management page

- app/pages/paths/management/ManageMentoring.vue
> fix: reduce dropdown font size in mentoring management

- app/pages/paths/management/ManageMentoring.vue
> fix: changed grade index in mentoring edit modal

- app/pages/paths/management/ManageMentoring.vue
- app/src/api/mentoring/mentoring.service.js
Closes #243 
- 또한 **방과후신청 관리**와 같게 각 버튼 `margin`을 수정했습니다.
> feat: mentoring list download button

- app/src/api/mentoring/mentoring.struct.js
- package-lock.json
> refactor(api): change mentoring register payload

- app/dimiru/components/DimiDropdown.vue
Closes #231 
본격 슈뢰딩거의 드롭다운 디버깅
> fix(ui): set background color in DimiDropdown

- app/pages/paths/management/ManageAssignment.vue
> fix: loading assignment data in edit model

- app/pages/paths/management/ManageAssignment.vue
> fix: timestamp comparison in assignment delete button

- app/pages/paths/assignment/Assignment.vue
> feat: assignment filter that hides ended assignments

- app/src/api/etcs/etcs.service.js
> feat: add error handler for etc request that passed deadline

- app/pages/paths/management/ManageEtc.vue
- app/pages/paths/request/Etcs.vue
> fix(style): remove useless border in etc request/management page

- app/pages/paths/request/Information.vue
> feat: add ingang, afterschool status in request status page

- app/pages/paths/request/Information.vue
> feat: change priority of requests information

- app/pages/paths/request/Information.vue
- app/src/api/afterschool/afterschool.service.js
> feat: today afterschool api for request info

- app/pages/paths/management/ManageMentoring.vue
- app/src/api/mentoring/mentoring.service.js
- app/src/api/mentoring/mentoring.struct.js
> feat: mentoring blacklist management

- app/pages/paths/management/ManageMentoring.vue
> feat: add helper message for empty blacklist

- app/pages/paths/management/ManageIngang.vue
- app/pages/paths/request/Ingang.vue
- app/src/api/ingang/ingang.service.js
- app/src/api/ingang/ingang.struct.js
> feat: ingang appliers list

- app/pages/paths/management/ManageIngang.vue
- app/pages/paths/request/Ingang.vue
> fix: listing ingang appliers logic

- app/src/api/assignment/assignment.struct.js
> fix: restructure assignment structure

- app/pages/paths/request/Information.vue
> feat: change priority of request statuses

- app/pages/paths/management/ManageAfterschool.vue
> fix: delete checked afterschool classes function

- app/pages/paths/management/ManageAfterschool.vue
- app/pages/paths/request/Afterschool.vue
- app/src/api/afterschool/afterschool.service.js
- app/src/api/afterschool/afterschool.struct.js
> feat: new afterschool request system

- app/pages/paths/request/Afterschool.vue
> feat: change mobile layout

- app/pages/paths/request/Information.vue
> fix: afterschool list in request information page

- app/components/MealGroup.vue
- app/pages/paths/auth/Login.vue
- app/src/api/meal/meal.service.js
> feat: show tomorrow meal after dinner

- app/src/api/ingang/ingang.service.js
> fix: error handler for canceling deadline-passed ingang room

- app/pages/paths/management/ManageIngang.vue
- app/src/api/ingang/ingang.service.js
- app/src/api/ingang/ingang.struct.js
백엔드에서 user_idx 대신 학번으로 받을 수 있게 바뀌면 머지해주세요
> feat: ingang blacklist

- app/pages/paths/management/ManageIngang.vue
> fix: order ingang applies by grade

- app/pages/paths/management/ManageAfterschool.vue
- app/src/api/afterschool/afterschool.service.js
- app/src/api/afterschool/afterschool.struct.js
> feat: bulk change method for afterschool request time

- app/dimiru/components/DimiDateInput.vue
> fix: DimiDateInput value error

- app/pages/paths/management/ManageAfterschool.vue
> fix: ManageAfterschool modal request manage error

- app/pages/paths/management/ManageAfterschool.vue
디미 데이트 인풋 에러 때문에 임시로 기존 시간 보여줌
> feat: show old afterschool request term

- app/App.vue
- app/scss/theme.scss
- package.json
- yarn.lock
> feat: snow for the winter

- app/App.vue
Sweetalert 알림창이 제대로 없는 문제 표시 => Sweetalert CSS 전역임포트
> fix: add css file
